apiVersion: apps/v1
kind: Deployment
metadata:
  name: $widget;format="lower,hyphen"$-web-deployment
  namespace: data-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $widget;format="lower,hyphen"$-web
  template:
    metadata:
      labels:
        app: $widget;format="lower,hyphen"$-web
    spec:
      containers:
      - name: $widget;format="lower,hyphen"$-web
        image: $org;format="lower"$/$image$:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: $widget;format="lower,hyphen"$-sidecar
        image: kindservices/datamesh-service-registry-client:latest
        imagePullPolicy: Always
        env:
          - name: HOSTPORT
            value: "http://service-registry-service.data-mesh:8080"
          - name: ID
            value: $widget;format="lower,hyphen"$-web
          - name: FREQUENCY_IN_SECONDS
            value: "3"
          - name: BODY
            value: '{"webComponent":{"jsUrl":"http://$widget;format="lower,hyphen"$-web.data-mesh/bundle.js","cssUrl":"http://$widget;format="lower,hyphen"$-web.data-mesh/bundle.css","componentId":"<$widget$ param_one=\"some param\"></$widget$>"},"label":"$name$","tags":{"props":"param_one"}}'
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: $widget;format="lower,hyphen"$-web
  namespace: data-mesh
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: $widget;format="lower,hyphen"$-web
  ports:
  - name : default
    port: 80
    targetPort: 80